project:
  type: book
  output-dir: docs

book:
  title: "Jackson Heart Study - Stroke Survival Analysis"
  subtitle: "STA6257 - Group Project"
  author: "Elizabeth, Chad, Emily"
  date: "11/02/2022"
  chapters:
    - index.qmd
    - part1.qmd
    - part2.qmd
    - part3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source
