# Part 3: Data Analysis

INtro
materials/methods
results
interpretation - discussion

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(haven)
library(table1)
library(lubridate)
library(survival)
library(ggsurvfit)
library(gtsummary)

#library(tidycmprsk)
#library(condSURV)
```

## Data Dictionary

SubjID
: Subject identification number for patient
 
VisitDate
 : Date of the subject's visit 1
 
Age
 : Age (in years) of subject at time of visit 1


## Summary statistics



```{r, echo = FALSE, warning = FALSE, message = FALSE}

#load visit 1 data
datav1 <- read_dta("data/analysis1.dta")
visit1 <- datav1 %>% dplyr :: select(subjid, visitdate, age, htn, diab3cat, idealhealthsmk, bmi3cat, totchol3cat)

#visit1 <- visit1 %>% rename(visitdate_v1 = visitdate)

#load adjudicated data

#data_allevtstroke <- read_sas("data/allevtstroke.sas7bdat", NULL)
#allevtstroke <- data_allevtstroke %>% dplyr :: select(subjid, Stroke, OHDStroke, eventdate)

data_incevtstroke <- read_sas("data/incevtstroke.sas7bdat", NULL)
incevtstroke <- data_incevtstroke %>% dplyr :: select(subjid, stroke, date, contactType)

#allevtstroke <- allevtstroke %>% rename(stroke_allevt = Stroke, ohdstroke = OHDStroke)

incevtstroke <- incevtstroke %>% rename(contacttype = contactType)

#data_adj <- full_join(allevtstroke, incevtstroke, by = "subjid")

# Create final data set

data <- full_join(incevtstroke, visit1, by = "subjid")
data <- na.omit(data)

###Example Code
# v1$hsgrad <- as.factor(v1$hsgrad)
# v1$bmi3cat <- as.factor(v1$bmi3cat)
# v1$htn <- as.factor(v1$htn)
# 
# label(v1$hsgrad) <- "High School Graduate"
# label(v1$bmi3cat) <- "AHA BMI Categorization"
# label(v1$htn) <- "Hypertension Status"
# 
# levels(v1$hsgrad) <- c("Nongraduate", "Graduate")
# levels(v1$bmi3cat) <- c("Poor", "Intermediate", "Ideal")
# levels(v1$htn) <- c("Normotensive", "Hypertensive")
# 
# table1(~ htn + age + totchol + hba1c + hsgrad + bmi3cat, data=v1)

table1(~ as.factor(stroke) + contacttype + age+ as.factor(htn) + as.factor(diab3cat) + as.factor(idealhealthsmk) + as.factor(bmi3cat)+ as.factor(totchol3cat) , data = data)
```


```{r, echo = FALSE, warning = FALSE, message = FALSE}

#Create time variable (time from visit 1 until event/censoring date)
data <- data %>% mutate(time = difftime(date, visitdate))

#Create the survival object (created from time variable and if the event has taken place.)
obj <- Surv(data$time, data$stroke)
```


## K-M Plot
```{r, echo = FALSE, warning = FALSE, message = FALSE}
km <- survfit(obj ~1, data=data)

#km_struct <- str(km)

km_2 <- survfit2(obj ~ 1, data=data)

km_plot <- km_2 %>% ggsurvfit() + labs(x = "Time in Days", y = "Overall probability Being Stroke Free") +   add_confidence_interval() + add_risktable()

km_plot
```



## Cox Proportion Hazards Model
```{r, echo = FALSE, warning = FALSE, message = FALSE}


cox <- coxph(obj ~ age + as.factor(htn) + as.factor(diab3cat) + as.factor(idealhealthsmk) + as.factor(bmi3cat)+ as.factor(totchol3cat), data=data)

cox_table <- cox %>% tbl_regression(exp = TRUE) 
cox_table
```


## Assumption Verification

```{r, echo = FALSE, warning = FALSE, message = FALSE}

##Colinearity

##LOF

##AIC

```
