# References {.unnumbered}


Bradburn, M.J., Clark, T.G., Love, S.B., & Altman, D.G. (2003). Survival Analysis Part II: Multivariate data analysis - an introduction to concepts and methods. *British Journal of Cancer, 89*(3), 431--436. https://doi.org/10.1038/sj.bjc.6601119

Centers for Disease Control and Prevention \> FastStats Homepage \> Life Stages and Populations \> Deaths (September 6, 2022). Retrieved November 2, 2022, from https://www.cdc.gov/nchs/fastats/leading-causes-of-death.htm

Centers for Disease Control and Prevention \> Stroke Home \> Stroke Statistics and Maps (October 14, 2022). Retrieved November 2, 2022, from https://www.cdc.gov/stroke/facts.htm.

Centers for Disease Control and Prevention \> Stroke Home \> Know Your Risk for Stroke (April 12, 2022). Retrieved November 2, 2022, from https://www.cdc.gov/stroke/risk_factors.htm.

Clark, T.G., Bradburn, M.J., Love, S.B., & Altman, D.G. (2003). Survival Analysis Part I: Basic concepts and first analyses. *Br J Cancer 89*, 232--238. https://doi.org/10.1038/sj.bjc.6601118

Keku, E., Rosamond, W. D. Taylor, H. A., Garrison, R. J., Wyatt, S. B., Richard, M., Campbell Jenkins, B.W., Reeves, L. & Sarpong. D.F. (2004). Cardiovascular disease event classification in the Jackson Heart Study: methods and procedures. *Ethnicity & Disease, 15*(4 Suppl 6), S6-70. https://pubmed.ncbi.nlm.nih.gov/16317987

Linden, A., Adams, J. & Roberts, N. (2004). Evaluating Disease Management Program Effectiveness: An Introduction to Survival Analysis. *Disease management : DM. 7*. 180-90. 10.1089/1093507042264818.

Longstreth, W.T. Jr., Gasca, N.C., Gottesman, R.F., Pearce, J.B. & Sacco, R.L. (2018) Adjudication of Transient Ischemic Attack and Stroke in the Multi-Ethnic Study of Atherosclerosis. *Neuroepidemiology. 50*(1-2), 23-28. doi: 10.1159/000486174. Epub 2018 Jan 11. PMID: 29324452; PMCID: PMC5860960

National Institute of Neurological Disorders and Stroke (n.d.). Retrieved November 2, 2022, from https://www.ninds.nih.gov/health-information/disorders/stroke

RDocumentation (n.d.). Retrieved October 9, 2022. https://www.rdocumentation.org/

Sempos, C.T., Bild D.E., & Manolio, T.A. (1999) Overview of the Jackson Heart Study: A Study of Cardiovascular Diseases in African American Men and Women, *The American Journal of the Medical Sciences, 317*(3),142-146, ISSN 0002-9629, https://doi.org/10.1016/S0002-9629(15)40495-1.

Sullivan, P.S., McKenna, M.T., Waller, L.A., Williamson, G. D., & Lee, L.M. (2010). Analyzing and Interpreting Public Health Surveillance Data. In L.M. Lee, S.M.Teutsch, S.B. Thacker, & M.E. St. Louis, *Principles & Practice of Public Health Surveillance, Third Edition*, (pp.88 - 145). Oxford University Press.

Wyatt S.B., Diekelmann N., Henderson F., Andrew M.E., Billingsley G., Felder, S.H. et al.(2003). A community-driven model of research participation: the Jackson Heart Study Participant Recruitment and Retention Study. *Ethn Dis, 13*(4):438-455.

Zabor, E. C. (October 19,2022). *Survival Analysis in R.* Retrieved October 28, 2022, from https://www.emilyzabor.com/tutorials/survival_analysis_in_r\_tutorial.htm
